api = "0.7"

[buildpack]
  description = "A buildpack for installing the appropriate Go compiler distribution version"
  homepage = "https://github.com/initializ-buildpacks/go-dist"
  id = "initializ-buildpacks/go-dist"
  keywords = ["go", "distribution", "compiler"]
  name = "Initializ Buildpack for Go Distribution"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/initializ-buildpacks/go-dist/blob/main/LICENSE"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    go = "1.21.*"

  [[metadata.dependencies]]
    checksum = "sha256:121ab58632787e18ae0caa8ae285b581f9470d0f6b3defde9e1600e211f583c5"
    cpe = "cpe:2.3:a:golang:go:1.21.12:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    purl = "pkg:generic/go@go1.21.12?checksum=121ab58632787e18ae0caa8ae285b581f9470d0f6b3defde9e1600e211f583c5&download_url=https://go.dev/dl/go1.21.12.linux-amd64.tar.gz"
    source = "https://go.dev/dl/go1.21.12.src.tar.gz"
    source-checksum = "sha256:30e68af27bc1f1df231e3ab74f3d17d3b8d52a089c79bcaab573b4f1b807ed4f"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.21.12.linux-amd64.tar.gz"
    version = "1.21.12"

  [[metadata.dependencies]]
    checksum = "sha256:502fc16d5910562461e6a6631fb6377de2322aad7304bf2bcd23500ba9dab4a7"
    cpe = "cpe:2.3:a:golang:go:1.21.13:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    purl = "pkg:generic/go@go1.21.13?checksum=502fc16d5910562461e6a6631fb6377de2322aad7304bf2bcd23500ba9dab4a7&download_url=https://go.dev/dl/go1.21.13.linux-amd64.tar.gz"
    source = "https://go.dev/dl/go1.21.13.src.tar.gz"
    source-checksum = "sha256:71fb31606a1de48d129d591e8717a63e0c5565ffba09a24ea9f899a13214c34d"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.21.13.linux-amd64.tar.gz"
    version = "1.21.13"

  [[metadata.dependencies]]
    checksum = "sha256:fc5d49b7a5035f1f1b265c17aa86e9819e6dc9af8260ad61430ee7fbe27881bb"
    cpe = "cpe:2.3:a:golang:go:1.22.7:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    purl = "pkg:generic/go@go1.22.7?checksum=fc5d49b7a5035f1f1b265c17aa86e9819e6dc9af8260ad61430ee7fbe27881bb&download_url=https://go.dev/dl/go1.22.7.linux-amd64.tar.gz"
    source = "https://go.dev/dl/go1.22.7.src.tar.gz"
    source-checksum = "sha256:66432d87d85e0cfac3edffe637d5930fc4ddf5793313fe11e4a0f333023c879f"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.22.7.linux-amd64.tar.gz"
    version = "1.22.7"

  [[metadata.dependencies]]
    checksum = "sha256:5f467d29fc67c7ae6468cb6ad5b047a274bae8180cac5e0b7ddbfeba3e47e18f"
    cpe = "cpe:2.3:a:golang:go:1.22.8:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    purl = "pkg:generic/go@go1.22.8?checksum=5f467d29fc67c7ae6468cb6ad5b047a274bae8180cac5e0b7ddbfeba3e47e18f&download_url=https://go.dev/dl/go1.22.8.linux-amd64.tar.gz"
    source = "https://go.dev/dl/go1.22.8.src.tar.gz"
    source-checksum = "sha256:df12c23ebf19dea0f4bf46a22cbeda4a3eca6f474f318390ce774974278440b8"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.22.8.linux-amd64.tar.gz"
    version = "1.22.8"

  [[metadata.dependency-constraints]]
    constraint = "1.21.*"
    id = "go"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "1.22.*"
    id = "go"
    patches = 2

[[stacks]]
  id = "*"
