api = "0.7"

[buildpack]
  description = "A buildpack for installing the appropriate Go compiler distribution version"
  homepage = "https://github.com/initializ-buildpacks/go-dist"
  id = "initializ-buildpacks/go-dist"
  keywords = ["go", "distribution", "compiler"]
  name = "Initializ Buildpack for Go Distribution"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/initializ-buildpacks/go-dist/blob/main/LICENSE"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    go = "1.26.*"

  [[metadata.dependencies]]
    checksum = "sha256:1fc94b57134d51669c72173ad5d49fd62afb0f1db9bf3f798fd98ee423f8d730"
    cpe = "cpe:2.3:a:golang:go:1.24.13:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    purl = "pkg:generic/go@go1.24.13?checksum=1fc94b57134d51669c72173ad5d49fd62afb0f1db9bf3f798fd98ee423f8d730&download_url=https://go.dev/dl/go1.24.13.linux-amd64.tar.gz"
    source = "https://go.dev/dl/go1.24.13.src.tar.gz"
    source-checksum = "sha256:639a6204c2486b137df1eb6e78ee3ed038f9877d0e4b5a465e796a2153f858d7"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.24.13.linux-amd64.tar.gz"
    version = "1.24.13"

  [[metadata.dependencies]]
    checksum = "sha256:00859d7bd6defe8bf84d9db9e57b9a4467b2887c18cd93ae7460e713db774bc1"
    cpe = "cpe:2.3:a:golang:go:1.25.9:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    purl = "pkg:generic/go@go1.25.9?checksum=00859d7bd6defe8bf84d9db9e57b9a4467b2887c18cd93ae7460e713db774bc1&download_url=https://go.dev/dl/go1.25.9.linux-amd64.tar.gz"
    source = "https://go.dev/dl/go1.25.9.src.tar.gz"
    source-checksum = "sha256:0ec9ef8ebcea097aac37decae9f09a7218b451cd96be7d6ed513d8e4bcf909cf"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.25.9.linux-amd64.tar.gz"
    version = "1.25.9"

  [[metadata.dependencies]]
    checksum = "sha256:990e6b4bbba816dc3ee129eaeaf4b42f17c2800b88a2166c265ac1a200262282"
    cpe = "cpe:2.3:a:golang:go:1.26.2:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    purl = "pkg:generic/go@go1.26.2?checksum=990e6b4bbba816dc3ee129eaeaf4b42f17c2800b88a2166c265ac1a200262282&download_url=https://go.dev/dl/go1.26.2.linux-amd64.tar.gz"
    source = "https://go.dev/dl/go1.26.2.src.tar.gz"
    source-checksum = "sha256:2e91ebb6947a96e9436fb2b3926a8802efe63a6d375dffec4f82aa9dbd6fd43b"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.26.2.linux-amd64.tar.gz"
    version = "1.26.2"

  [[metadata.dependency-constraints]]
    constraint = "1.24.*"
    id = "go"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "1.25.*"
    id = "go"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "1.26.*"
    id = "go"
    patches = 1

[[stacks]]
  id = "*"
